apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "ingest-src-mssql-sales"
  namespace: kafka
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: kafka-class
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    connection.url: "jdbc:sqlserver://ney-database-source-kafka.ctwliq6jzx6a.us-east-1.rds.amazonaws.com:1433;databaseName=dw"
    connection.user: "${file:/opt/kafka/external-configuration/connector-config-mssql/mssql-credentials.properties:mssql_username}"
    connection.password: "${file:/opt/kafka/external-configuration/connector-config-mssql/mssql-credentials.properties:mssql_password}"
    connection.attempts: "2"
    query: "SELECT * FROM dbo.sales"
    mode: "timestamp"
    topic.prefix: "mssql-sales"
    timestamp.column.name: "dt_update"
    validate.non.null: "false"
    transforms: "createKey,extractInt,InsertTopic,InsertSourceDetails"
    transforms.createKey.type: "org.apache.kafka.connect.transforms.ValueToKey"
    transforms.createKey.fields: "dt_update"
    transforms.extractInt.type: "org.apache.kafka.connect.transforms.ExtractField$Key"
    transforms.extractInt.field: "dt_update"
    transforms.InsertTopic.type: "org.apache.kafka.connect.transforms.InsertField$Value"
    transforms.InsertTopic.topic.field: "messagetopic"
    transforms.InsertSourceDetails.type: "org.apache.kafka.connect.transforms.InsertField$Value"
    transforms.InsertSourceDetails.static.field: "messagesource"
    transforms.InsertSourceDetails.static.value: "sqlserver"
